### ISSUE TITLE
Página de Entregas

### ISSUE THREAD

**Issue by luciano-freitas-melo** [Requisitos-de-Software/2022.2-GoogleMaps#56]
### O que deve ser feito?
Inserir as apresentações das etapas do projeto e formatar o artefato seguindo as padronizações do projeto.

### Tasks
- [ ] Fazer os tópicos do artefato
- [ ] Tentar colocar os vídeos no artefato (caso não consiga, colocar os links para os vídeos)
- [ ] Não esquecer das legendas e fazer as referências aos vídeos nos textos
